---
- hosts: localhost
  tasks:
    - name: Setup pacman config
      copy: src=files/etc/pacman.conf dest=/etc/pacman.conf owner=root
    - name: Setup pacman mirrorlist
      copy: src=files/etc/pacman.d/mirrorlist dest=/etc/pacman.d/mirrorlist owner=root
    - name: Sync pacman
      pacman: update_cache=yes
      sudo: yes
    - name: Copy yaourt install script for AUR access
      copy: src=files/usr/local/bin/install-yaourt.sh dest=/usr/local/bin/install-yaourt.sh
      sudo: yes
    - name: Run yaourt install script
      command: /bin/bash /usr/local/bin/install-yaourt.sh
      sudo: yes
    - name: Install VIM
      pacman: pkg=vim state=present
      sudo: yes
    - name: Install NTP
      pacman: pkg=ntp state=present
    - name: Install Glances
      pacman: pkg=glances state=present
      sudo: yes
    - name: Install Firefox
      pacman: pkg=firefox state=present
      sudo: yes
    - name: Install Thunderbird
      pacman: pkg=thunderbird state=present
      sudo: yes
    - name: Install Syncthing
      pacman: pkg=syncthing state=present
      sudo: yes
    - name: Install Wine
      pacman: pkg=wine state=present
      sudo: yes
    - name: Install KeepassX
      pacman: pkg=keepassx state=present
      sudo: yes
    - name: Install ZFS modules
      command: yaourt -S --noconfirm zfs-git
    - name: Install Rsync
      pacman: pkg=rsync state=present
    - name: Install F-Lux 
      command: yaourt -S --noconfirm fluxgui
    - name: Install Meld ( diff tool )
      command: yaourt -S --noconfirm meld
    - name: Install YouCompleteMe vim plugin
      command: yaourt -S --noconfirm vim-youcompleteme-git
    - name: Install Spotify ( need the tunes! )
      command: yaourt -S --noconfirm spotify
    - name: Install Skype
      command: yaourt -S --noconfirm skype
