- name: Setup pacman.conf
  template: src=pacman.conf dest=/etc/pacman.conf owner=root
  sudo: yes

- name: Setup pacman mirrorlist
  copy: src=mirrorlist dest=/etc/pacman.d/mirrorlist owner=root
  sudo: yes

- name: Sync pacman
  pacman: update_cache=yes
  sudo: yes

- name: Install base packages
  pacman: pkg={{ item }} state=present
  sudo: yes
  with_items: 
    - ecryptfs-utils
    - vim
    - ntp
    - glances
    - firefox
    - syncthing
    - wine
    - keepassx
    - rsync
    - git
    - terminology
    - openvpn
    - networkmanager-openvpn
    - networkmanager-pptp
    - gpsd
    - vlc
    - mtr

- name: install aur.sh
  file: src=aur.sh dest=/home/alan/aur.sh owner=alan group=alan
  tags:
    - aursh

- name: install aur packages with aur.sh
  shell: "cd /home/alan/aur && /bin/bash /home/alan/aur.sh -sf {{ item }}"
  with_items:
    - package-query
    - yaourt

- name: install aur packages with aur.sh
  shell: "cd /home/alan/aur && pacman -U --force {{ item }}/*.pkg.tar.xz"
  sudo: yes
  ignore_errors: yes
  with_items:
    - package-query
    - yaourt

- name: install yaourtrc file
  copy: src=yaourtrc dest=/home/alan/.yaourtrc

- name: install vimrc file
  copy: src=vimrc dest=/home/alan/.vimrc owner=alan group=alan

- name: setup GNOME
  command: dconf write {{ item }} true
  with_items:
   - /org/gnome/desktop/interface/clock-show-date
   - /org/gnome/desktop/interface/clock-show-seconds

- name: setup GNOME HiDPI
  command: dconf write /org/gnome/desktop/interface/scaling-factor 2
  when: ansible_product_name == "XPS 13 9343"
