---
- name: Setup pacman config
  template: src=pacman.conf dest=/etc/pacman.conf owner=root
  sudo: yes

- name: Setup pacman mirrorlist
  copy: src=mirrorlist dest=/etc/pacman.d/mirrorlist owner=root
  sudo: yes

- name: Sync pacman
  pacman: update_cache=yes
  sudo: yes

- name: Install base packages
  pacman: pkg={{ item }} state=present
  sudo: yes
  with_items: 
    - ecryptfs-utils
    - vim
    - ntp
    - glances
    - firefox
    - syncthing
    - wine
    - keepassx
    - rsync
    - git
    - terminology
    - openvpn
    - networkmanager-openvpn
    - gpsd

- name: install aur.sh
  file: src=aur.sh dest=/home/alan/aur.sh owner=alan group=alan state=touch
  tags:
    - aursh
    
- name: install aur packages with aur.sh
  shell: "/bin/bash /home/alan/aur.sh -si {{ item }}"
  sudo: yes
  with_items:
    - package-query
    - yaourt
    - spotify
    - redshift-git
    - redshift-gtk-git

- name: install yaourtrc file
  copy: src=yaourtrc dest=/home/alan/.yaourtrc

- name: Install AUR packages
  command: yaourt -Sy --noconfirm {{ item }}
  with_items:
    - meld
    - skype
  sudo: yes

- name: Install AUR packages when not on low power device
  command: yaourt -Sy --noconfirm {{ item }}
  with_items:
    - vim-youcompleteme-git
  when: ansible_product_name != 'NC10'

- name: install vimrc file
  file: src=vimrc dest=/home/alan/.vimrc owner=alan group=alan

- name: setup GNOME
  command: dconf write {{ item }} true
  with_items:
   - /org/gnome/desktop/interface/clock-show-date
   - /org/gnome/desktop/interface/clock-show-seconds
   
- name: start services
  service: name=gpsd status=started enabled=yes
  sudo: yes
