---

- name: download tarball
  get_url: url=https://github.com/syncthing/syncthing/releases/download/v{{ syncthing_version }}/syncthing-linux-386-v{{ syncthing_version }}.tar.gz  dest=/tmp/syncthing-linux-386-v{{ syncthing_version }}.tar.gz
- name: extract syncthing tarball
  unarchive: src=/tmp/syncthing-linux-386-v{{ syncthing_version }}.tar.gz dest=/tmp/
- name: copy syncthing bin file
  copy: src=/tmp/syncthing-linux-386-v{{ syncthing_version }}/syncthing dest=/usr/local/bin/syncthing owner=root group=root mode="u=rwx,g=rx,o=rx"
  notify: restart syncthing
- name: copy syncthing upstart file
  copy: src=syncthing.conf dest=/etc/init/syncthing.conf owner=root group=root mode="u=rw,g=r,o=r"
  notify: restart syncthing
- name: ensure syncthing config directory is present
  file: path=/home/alan/.config/syncthing state=directory owner=alan group=alan mode="u=rwx,g=r,o=r"
- name: clean up
  file: path=/tmp/syncthing-linux-386-v{{ syncthing_version }}.tar.gz state=absent
- name: more clean up
  file: path=/tmp/syncthing-linux-386-v{{ syncthing_version }} state=absent
