---

- name: include Arch Linux specific tasks when on Arch
  include: arch.yml
  when: ansible_lsb.description == "Arch Linux"
- name: include Ubuntu Linux specific tasks when on Ubuntu
  include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
- name: install vimrc file
  copy: src=vimrc dest=/home/alan/.vimrc owner=alan group=alan
  
