---

- name: include Arch Linux specific tasks when on Arch
  include: arch.yml
  when: ansible_distribution == "Arch"
- name: include Arch Linux specific tasks when on Arch
  include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: install vimrc file
  copy: src=vimrc dest=/home/alan/.vimrc owner=alan group=alan
