---

- name: include Arch Linux specific tasks when on Arch
  include: arch.yml
  when: ansible_distribution == "Arch"
- name: include Ubuntu Linux specific tasks when on Ubuntu
  include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
- name: include Home based specific tasks when on work laptop
  include: home.yml
  when: ansible_product_name != "Dell System XPS L702X"
- name: include Work based specific tasks on work laptop
  include: work.yml
  when: ansible_product_name == "Dell System XPS L702X"
- name: install vimrc file
  copy: src=vimrc dest=/home/alan/.vimrc owner=alan group=alan
  
