---

- name: Remove some base packages
  apt: name={{ item }} state=absent purge=yes
  with_items:
    - ntp
    - libreoffice*
    - thunderbird*

- name: Install base packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: 
    - vim
    - openntpd
    - glances
    - wine
    - rsync
    - finch
    - openvpn
    - network-manager-openvpn
    - redshift-gtk
    - stellarium
    - meld
    - subversion
    - python-apt

- name: Add external PPAs
  apt_repository: repo={{ item }} state=present
  with_items:
    - 'ppa:webupd8team/sublime-text-3'
    - 'ppa:ytvwld/syncthing'

- name: Add external packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - sublime-text-installer
    - syncthing

- name: Add Spotify Repo
  apt_repository: repo='deb http://repository.spotify.com stable non-free'
- name: Add Spotify Key
  apt_key: keyserver=keyserver.ubuntu.com id=94558F59
- name: Install Spotify
  apt: name=spotify-client state=present update_cache=yes
