---

- name: Upgrade all packages
  apt: upgrade=dist

- name: Remove some base packages
  apt: name={{ item }} state=absent purge=yes
  with_items:
    - ntp
    - libreoffice*
    - thunderbird*

- name: Install base packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: 
    - vim
    - openntpd
    - glances
    - wine
    - rsync
    - openvpn
    - network-manager-openvpn
    - redshift-gtk
    - meld
    - subversion
    - python-apt
    - python-dev
    - dconf-tools
    - clusterssh
    - pdsh
    - zsh
    - keepassx

- name: Add external PPAs
  apt_repository: repo={{ item }} state=present
  with_items:
    - 'ppa:webupd8team/sublime-text-3'
    #- 'ppa:enlightenment-git/ppa'
    #- 'ppa:adiscon/v8-stable'
    - 'ppa:ytvwld/syncthing'
    - 'ppa:nilarimogard/webupd8'

- name: Add external packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - sublime-text-installer
    - terminology
    - rsyslog
    - syncthing
    - syncthing-gtk

- name: Add Spotify Repo
  apt_repository: repo='deb http://repository.spotify.com stable non-free'
- name: Add Spotify Key
  apt_key: keyserver=keyserver.ubuntu.com id=94558F59
- name: Install Spotify
  apt: name=spotify-client state=present update_cache=yes

- name: setup Unity how I likes it
  shell: gsettings set {{ item.schema }} {{ item.key }} {{ item.value }}
  with_items:
    - { schema: 'com.canonical.Unity.Lenses', key: 'remote-content-search', value: 'none' }
    - { schema: 'com.canonical.indicator.datetime', key: 'show-date', value: 'true' }
    - { schema: 'com.canonical.indicator.datetime', key: 'show-seconds', value: 'true' }
    - { schema: 'com.canonical.indicator.datetime', key: 'show-day', value: 'true' }
    - { schema: 'com.canonical.indicator.datetime', key: 'show-auto-detected-location', value: 'true' }
    - { schema: 'com.canonical.indicator.datetime', key: 'show-locations', value: 'true' }
    - { schema: 'com.canonical.indicator.datetime', key: 'locations', value: "\"['Australia/Sydney Sydney','Europe/Prague Prague','America/Vancouver Kamloops']\"" }
    - { schema: 'com.canonical.indicator.power', key: 'show-percentage', value: 'true' }

- name: install Python packages
  pip: name=glances

- name: Newsweaver PPTP config file setup
  copy: src="etc/NetworkManager/system-connections/Newsweaver PPTP" dest="/etc/NetworkManager/system-connections/Newsweaver PPTP" owner=root group=root mode="u=rw,g=,o="
  sudo: yes

- name: ensure ssh config
  copy: src=config dest=/home/alan/.ssh/config owner=alan group=alan mode="u=rw,g=,o="

- name: Allow standard user to control Docker containers
  user: name=alan append=yes groups=docker
  notify: restart docker
