---

- name: Install work packages
  pacman: name={{ item }} state=present update_cache=yes
  with_items: 
    - clusterssh
    - pdsh
    - zsh
    - keepassx
    - docker
  sudo: yes

- name: enable and start docker
  service: name=docker state=started

- name: Install work packages with yaourt
  shell: yaourt -S {{ item }}
  with_items:
    - sublime-text-nightly
    - oh-my-zsh-git
  sudo: yes
  sudo_user: alan

- name: Copy .zshrc file
  copy: src="home/alan/.zshrc" dest="/home/alan/.zshrc" owner=alan group=alan
- name: Ensure permissions of .zshrc
  file: name=/home/alan/.zshrc owner=alan group=alan
- name: Ensure permissions .oh-my-zsh
  file: name=/home/alan/.oh-my-zsh owner=alan group=alan state=directory recurse=yes
