---

- name: Install work packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: 
    - clusterssh
    - pdsh
    - zsh
    - keepassx

- name: Install Oh-My-ZSH
  git: repo=git://github.com/robbyrussell/oh-my-zsh.git dest=/home/alan/.oh-my-zsh clone=yes accept_hostkey=true
  sudo: no

- name: Copy zshrc file
  shell: "cp /home/alan/.oh-my-zsh/templates/zshrc.zsh-template /home/alan/.zshrc && chsh -s /bin/zsh alan"
  sudo: no

- name: Ensure permissions of .zshrc
  file: name=/home/alan/.zshrc owner=alan group=alan

- name: Newsweaver PPTP config file setup
  copy: src="etc/NetworkManager/system-connections/Newsweaver PPTP" dest="/etc/NetworkManager/system-connections/Newsweaver PPTP" owner=root group=root mode="u=rw,g=,o="