---

- name: Install work packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: 
    - clusterssh
    - pdsh
    - zsh
    - keepassx

- name: Install Oh-My-ZSH
  git: repo=git://github.com/robbyrussell/oh-my-zsh.git dest=/home/alan/.oh-my-zsh clone=yes accept_hostkey=true
  sudo: no

- name: Copy zshrc file
  shell: "cp /home/alan/.oh-my-zsh/templates/zshrc.zsh-template /home/alan/.zshrc && chsh -s /bin/zsh alan"
  sudo: no

- name: Ensure permissions of .zshrc
  file: name=/home/alan/.zshrc owner=alan group=alan
- name: Ensure permissions .oh-my-zsh
  file: name=/home/alan/.oh-my-zsh owner=alan group=alan state=directory recurse=yes

- name: Newsweaver PPTP config file setup
  copy: src="etc/NetworkManager/system-connections/Newsweaver PPTP" dest="/etc/NetworkManager/system-connections/Newsweaver PPTP" owner=root group=root mode="u=rw,g=,o="

- name: Add Virtualbox Repo
  apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian trusty contrib'
- name: Add Virtualbox Key
  apt_key: url='https://www.virtualbox.org/download/oracle_vbox.asc' state=present
- name: Install Virtualbox 4.3
  apt: name=virtualbox-4.3 state=present update_cache=yes
